.TH TOPY 1 "jan 28, 2009"
.SH NAME
topy \- TCP server for realtime statistics
.SH USAGE
.HP 8
\fBtopy [option]
.RI
.SH DESCRIPTION
\fBTopy\fR is a TCP server designed to generate realtime statistics.
.RI
.SH OPTIONS
.TP
.B \-a, \-\-address <ip address>
Ip address to listen. Default adress is 0.0.0.0.

.TP
.B \-p, \-\-port <port>
Port to listen. Default port is 6969

.TP
.B \-r, \-\-restore <path>
Restore memory from dump file

.TP
.B \-R, \-\-restore-autodump <path>
Restore memory from autodump file

.TP
.B \-T, \-\-autodump-target <path>
Set path for autodump target

.TP
.B \-D, \-\-autodump-delay <sec>
Set pause after each autodump

.TP
.B \-P, \-\-pidfile <path>
Write the pid of the process to the given file

.TP
.B \-v, \-\-verbose
Turn on verbose output

.TP
.B \-c, \-\-conf <path>
Set path of configuration to use. Default path is /etc/topy.conf

.TP
.B \-v, \-\-version
Show the version number and exit

.TP
.B \-h, \-\-help
print this help and exit

.RI
.SH AUTHOR
\fBTopy\fR and this manual page were written by Nicolas Vion <nico@picapo.net>.


